### ISSUE TITLE
Wrong number of tasks in Pytorch Lightning example

### ISSUE THREAD

**Issue by magehrig** [PrincetonUniversity/multi_gpu_training#1]
In the Pytorch Lightning [Multi-GPU example](https://github.com/PrincetonUniversity/multi_gpu_training/tree/main/03_pytorch_lightning#step-3-submit-the-job), the number of tasks per node is set to 1 while the number of gpus per node is set to 2. This is not correct according to PL docs: https://pytorch-lightning.readthedocs.io/en/latest/clouds/cluster_advanced.html#troubleshooting
instead it should be the case that the number of tasks is equal to the number of gpus per node, as indicated in [README 02](https://github.com/PrincetonUniversity/multi_gpu_training/tree/main/02_pytorch_ddp#total-number-of-tasks-equals-total-number-of-gpus).

**Comment by jdh4** [comment]
The README file was indeed incorrect. The example Slurm script (job.slurm) was correct, however. The mistake in the README file has been corrected. Thank you for pointing this out.
