### ISSUE TITLE
Potential mistake in figure: Parallelize data loading

### ISSUE THREAD

**Issue by magehrig** [PrincetonUniversity/multi_gpu_training#2]
In the second row "parallelize data loading" of the [data loading figure](https://github.com/PrincetonUniversity/multi_gpu_training/tree/main/01_single_gpu#step-5-optimize-your-script), it appears that multiple workers load data for batch n and n+1. In Pytorch, each worker loads a whole batch, even in multiprocessing. In other words, parallelization across workers is inter-batch not intra-batch. It is mentioned in the [docs](https://pytorch.org/docs/stable/data.html#multi-process-data-loading):
_"At this point, the dataset, collate_fn, and worker_init_fn are passed to each worker, where they are used to initialize, and fetch data. This means that dataset access together with its internal IO, transforms (including collate_fn) **runs in the worker process**."_

It's a minor issue that does not really affect anyone but I wanted to point this out nonetheless.

**Comment by jdh4** [comment]
Thanks for the info.
